[tools]
"github:grctl/grctl" = "latest"
uv = "latest"

[tasks.worker]
description = "Start the worker"
run = "uv run python worker.py"

[tasks.client]
description = "Start the client"
run = "uv run python client.py"
